# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.CharField(max_length=50, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telephone',
            field=models.IntegerField(verbose_name='telefone'),
        ),
    ]
